### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by dries-c** [LegoCraftPE/legocraft.me#1]

**Comment by legoboy0215** [comment]
LOL

**Comment by dries-c** [comment]
I am closing my old issues
But can you join ng again?? Your discord is offlinee for ages

Op 30-dec.-2017 05:58 schreef "Legoboy0215" <notifications@github.com>:

**Comment by legoboy0215** [comment]
NG? As in NetherGames? Dang long time... I'll try :)

**Comment by dries-c** [comment]
yep nethergames :)

Op 30-dec.-2017 12:52 schreef "Legoboy0215" <notifications@github.com>:
